### ISSUE TITLE
辛苦大佬，一點小建議

### ISSUE THREAD

**Issue by Bonnie-Ran** [GiorgiZedelashvili/Photoshop-CS6#1]
谢谢，是的，我在这个程序中工作。 当应用程序将完全修复时，我上传源代码。 对不起谷歌翻译:)

**Comment by GiorgiZedelashvili** [comment]
谢谢，是的，我在这个程序中工作。 当应用程序将完全修复时，我上传源代码。 对不起谷歌翻译:)

**Comment by Bonnie-Ran** [comment]
> 谢谢，是的，我在这个程序中工作。 当应用程序将完全修复时，我上传源代码。 对不起谷歌翻译:)

Okay, hard work developer.
